name: Build and publish

on:
  push:
    branches:
      - "**"
      - "!dependabot/**"
  release:
    types: [created]

env:
  REGISTRY: ghcr.io
  JAVA_VERSION: 17

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=v{{version}}
            type=sha

      - name: Execute Gradle build
        run: |
          ./gradlew jib \
            -Djib.to.image==${{ env.REGISTRY }}/${{ github.repository }} \
            -Djib.to.tags="${{ steps.meta.outputs.tags }}" \
            -Djib.to.auth.username=${{ github.actor }} \
            -Djib.to.auth.password=${{ secrets.GITHUB_TOKEN }}
