name: Build and publish

on:
  push:
    branches:
      - "**"
      - "!dependabot/**"
  release:
    types: [created]

env:
  REGISTRY: ghcr.io
  JAVA_VERSION: 17

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: |
          ./gradlew clean build
          mkdir -p target/extracted
          java -Djarmode=layertools -jar build/libs/*.jar extract --destination target/extracted

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=v{{version}}
            type=sha

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          provenance: true
          push: true
          build-args: |
            JAVA_VERSION=${{ env.JAVA_VERSION }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
