name: Build and publish

on:
  push:
    branches:
      - "**"
      - "!dependabot/**"
  release:
    types: [created]

env:
  REGISTRY: ghcr.io
  JAVA_VERSION: 17

# We need this to be able to push to the container registry
permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: |
          ./gradlew jib \
            -Djib.console=plain \
            -Djib.to.image=${{ env.REGISTRY }}/${{ github.repository }} \
            -Djib.to.tags="${{ github.sha }}"
